# Generated by Django 3.0.7 on 2020-07-02 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя клиента')),
                ('typeSells', models.CharField(max_length=150, verbose_name='Тип заказа')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('costsType', models.CharField(max_length=500, verbose_name='Тип затрат')),
            ],
            options={
                'verbose_name': 'Расчет затрат',
                'verbose_name_plural': 'Расчеты затрат',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(max_length=150, verbose_name='Тип изделия')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Содержание')),
                ('serviceType', models.CharField(max_length=300, verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('sector', models.CharField(max_length=200, verbose_name='Отдел')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('dateOfStartWork', models.DateField(default=datetime.datetime.today, verbose_name='Начало работы')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.CharField(max_length=150, verbose_name='Студент')),
                ('sector', models.CharField(max_length=300, verbose_name='Отделение')),
                ('startLearningDate', models.DateField(default=datetime.datetime.today, verbose_name='Начало обучение')),
                ('endLearningDate', models.DateField(default=datetime.datetime.today, verbose_name='Конец обучения')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('deadline', models.DateField(default=datetime.datetime.today, verbose_name='Дата выполнения заказа')),
                ('contractor', models.ManyToManyField(to='database.Contractor', verbose_name='Поставщик')),
                ('productType', models.ManyToManyField(to='database.Product', verbose_name='Тип изделия')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='productType',
            field=models.ManyToManyField(to='database.Product', verbose_name='Тип изделий'),
        ),
    ]
