# Generated by Django 3.0.7 on 2020-07-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Заказ <built-in function id>', max_length=200, verbose_name='Название'),
        ),
    ]
