# Generated by Django 3.0.7 on 2020-07-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200703_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Заказ <built-in function id>', max_length=200, null=True, verbose_name='Название'),
        ),
    ]
